mybatis:
  type-aliases-package: tern.block.blockDTO,tern.block.pojo
  mapper-locations: classpath:mapper/*.xml
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/blockChain?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource 
  mail:
    host: smtp.163.com
    username: 13808547353@163.com
    password: wang0424
    default-encoding: UTF-8
  rabbitmq:
    host: 106.14.211.161
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  cloud:
    stream:
      bindings:
        nodeRegistryMessage:
          group: tern-blockchain-sys
          content-type: application/json
server:
  port: 8774
env: 
  dev
