spring:
  application:
    name: tern-blockchain-node
  profiles:
    active: dev
  rabbitmq:
    host: 192.168.99.100
    password: admin
    port: 5672
    username: admin
    virtual-host: /
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/blockChain?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
server:
  port: 8777
